export const BASE_URL = 'https://zyntrixfx.pythonanywhere.com/';

export const ENDPOINTS = {
  register: `${BASE_URL}auth/register`,
  login: `${BASE_URL}auth/login`,
  otp: `${BASE_URL}auth/otp`,
  verifyOtp: `${BASE_URL}auth/verify-otp`,
  resetPassword: `${BASE_URL}auth/reset-password`,
  dashboard: `${BASE_URL}user/dashboard`,
  transactionHistory: `${BASE_URL}user/history`,
  activeInvestments: `${BASE_URL}user/investments/active`,
  profits: `${BASE_URL}user/profits`,
  deposits: `${BASE_URL}user/deposits`,
  withdrawals: `${BASE_URL}user/withdrawals`,
  referrals: `${BASE_URL}user/referals`,
  paymentMethods: `${BASE_URL}super/payment-methods`,
  deposit: `${BASE_URL}user/deposit`,
  withdraw: `${BASE_URL}user/withdraw`,
  transfer: `${BASE_URL}user/transfer`,
  updateProfile: `${BASE_URL}user/profile/update`,
  withdrawalInfo: `${BASE_URL}user/profile/withdrawal`,
  createWithdrawalInfo: `${BASE_URL}user/profile/withdrawal/create`,
  otherSettings: `${BASE_URL}user/other-settings`,
  updateSettings: `${BASE_URL}user/settings/notifications`,
  changePassword: `${BASE_URL}auth/change-password`,
  plans: `${BASE_URL}super/plans`,
  createInvestment: `${BASE_URL}user/investments/create`,
  kycSubmit: `${BASE_URL}user/kyc/submit`,
  toggleAutoReinvest: (id: number | string) => `${BASE_URL}user/investment/${id}/toggle-auto-reinvest`,
  verifyAccount: (token: string) => `${BASE_URL}auth/verify/${token}`,
};
